### ISSUE TITLE
Servis za komunikaciju sa bazom podataka

### ISSUE THREAD

**Issue by ispeh** [MPodravac/AirTraffic#1]
Kreirati projekt CRUD tipa ClassLibrary unutar kojeg je potrebno definirati klasu CRUD koja ima metodu
AddCountry() - sprema novu državu u tablicu AirTraffic_countries
DeleteCountry() - briše državu 
UpdateCountry() - ažurira državu
GetAllCountries() - vraća sve države

**Comment by MPodravac** [comment]
Što mi sve tablica u bazi treba sadržavati? Da li je to ono što mi sve nabrojali (država, latituda, longituda, oznaka aviona) ili sve iz one tablice koju moram iskoristiti i za klasu Flight?

**Comment by ispeh** [comment]
Dodao sam još dva zadatka pa će vam biti jasnije. Dakle ovdje se radi o administraciji država (klasa Country, tablica countries). Kasnije ćemo koristiti ove tablice prilikom čitanja informacije o zračnom prometu (npr. daj mi sve letove koje idu prema Hrvatskoj i Italiji - ove dvije države su zapisane u tablici countries)

**Comment by MPodravac** [comment]
Ovako, za sada sam napravila ClassLibrary s klasom CRUD s funkcijama koje ste naveli da moram imati, također sam unutar tog projekta kreirala klasu Country (task 6), sve se povezuje s bazom preko SqlConnectionString-a kojeg sam navela u app config-u. Da li je to u redu?

**Comment by ispeh** [comment]
Slobodno postavite svoj kod u ovaj repozitorij, tako će biti lakše pratiit

**Comment by MPodravac** [comment]
evo, kod je postavljen

**Comment by ispeh** [comment]
Odlično. Načelno je sve u redu, ali to ćemo vidjeti tek kada upogonimo formu. Pokušavajte izbjegavati defaultna imena datoteka (Class1.cs, Form1.cs....) jer što ih više bude, to će biti teže pratiti. Class1.cs preimenovati u Crud.cs. Budući da zasada nema metoda koje bi ovdje dodavali, zaključavamo ovaj task.
