### ISSUE TITLE
GMap.NET

### ISSUE THREAD

**Issue by MPodravac** [MPodravac/AirTraffic#10]
Instalirati GMap.NET preko Manage NuGet packages i umetnuti mapu u karticu History AirTraffic (geo). Prikazati dva čvora na mapi (npr. Virovitica i Slatina).

**Comment by MPodravac** [comment]
Profesore, instalirala sam GMap.NET i pokušala prikazati dva čvora na mapi koji su označeni s dva različita markera. Postavila sam kod pa bih voljela da pogledate te date svoj komentar kako vam to izgleda. Kod pokretanja programa moguće je da se karta sporije učita (pročitala sam da se Google-ova mapa često sporije učitava od primjerice Bing-ove mape).

**Comment by ispeh** [comment]
Što se tiče mape, to je to. Eventualno bi se mapa trebala proširiti zajedno sa prozorom, ali to možete i na kraju. Ono što bi sada trebalo napraviti je funkcija SetFlightsOnMap koja bi se pozivala unutar gMapAirTraffic_Load (na mjestu gdje sad ručno kreriate markere). Funkcija SetFlightsOnMap ide po listi letova i jednostavno za svaki let kreira novi marker i postavlja ga na kartu. Brzinu učitavanja zanemarite, to ovisi o brzini interneta i jasno je da će ponekad biti sporije, ali na to ne možemo utjecati.

**Comment by MPodravac** [comment]
Nije mi baš bilo jasno gdje da napišem tu funkciju pa sam pokušala na svoj način unutar gMapAirTraffic_Load i letovi se prikazuju na mapi. Također sam postavila da se mapa proširuje zajedno s prozorom.

**Comment by ispeh** [comment]
Napišite ju kao zasebnu f-ju ispod gMapAirTraffic_Load
