### ISSUE TITLE
Servis za dohvaćanje letova

### ISSUE THREAD

**Issue by ispeh** [MPodravac/AirTraffic#2]
Kreirati projekt RESTapi tipa ClassLibrary unutar kojeg je potrebno definirati klasu REST koja ima metodu GetFlights(). Metoda pozivom rest api-ja vraća i parsira JSON u listu objekata klase Flight. Let se sprema u listu samo ako se origin-country nalazi u bazi država.

**Comment by ispeh** [comment]
**Let se sprema u listu samo ako se origin-country nalazi u bazi država.**  Dakle, potrebno je provjeriti da li se država nalazi spremljena u bazi.

**Comment by MPodravac** [comment]
Taj sam dio zadatka uspjela napraviti, no zaboravila sam postaviti novu verziju koda. Uglavnom, imam problem kod parsiranja json-a, konkretno kada su u pitanju varijable tipa int ili float i kada je njihova vrijednost null (a u većini slučajeva je), program ih ne može pretvoriti u int32 ili single i ne znam kako da taj problem riješim. Te varijable su u kodu zakomentirane, a ostavila sam string i bool, one se pravilno pokazuju.
