### ISSUE TITLE
Klasa Flight

### ISSUE THREAD

**Issue by ispeh** [MPodravac/AirTraffic#3]
Kreirati klasu Flight prema tablici 

![image](https://user-images.githubusercontent.com/8260310/33795656-f70a1556-dce5-11e7-99a9-d82ba44afa81.png)

koja se nalazi na https://opensky-network.org/apidoc/rest.html

**Comment by MPodravac** [comment]
Da li je u ovu klasu potrebno uvrstiti sve s tablice ili da sadrži samo osnovno, ono što ste mi rekli tokom dodjele zadatka (npr. iz ove tablice prvih šest elemenata)?
